# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5f2a4217-4ff7-462c-a3e9-70601ef87358";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."cryptrot1".device = "/dev/disk/by-uuid/07cf353c-aff3-4663-b7c6-c83355377092";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/5f2a4217-4ff7-462c-a3e9-70601ef87358";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5f2a4217-4ff7-462c-a3e9-70601ef87358";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/mnt/stor" =
    { device = "/dev/disk/by-uuid/8387acb7-5e0a-4359-babd-fa7a942e6f58";
      fsType = "btrfs";
      options = [ "subvol=stor" ];
    };

  boot.initrd.luks.devices."cryptstor".device = "/dev/disk/by-uuid/ee5737d8-61e1-42b6-92d7-be575f99e1e7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/53A4-9DFD";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/909f3c62-12f5-4220-b224-facd2a6ce364"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
