{
  imports = [
    ./corectrl.nix
    ./fonts.nix
    ./gamemode.nix
    ./gnome.nix
    ./gpg.nix
    ./ledger.nix
    ./monero.nix
    ./nano.nix
    ./nix.nix
    ./pipewire.nix
    ./power-management.nix
    ./printing.nix
    ./steam.nix
    ./timesyncd.nix
    ./tor.nix
    ./zram.nix
  ];
}
